alias core='cd ~/projects/cdris_repo'
alias pi='cd ~/projects/cdris_patient_identity'
alias hcc='cd ~/projects/hcc_portal'
alias testui='cd ~/projects/cdris_test_ui'
alias repo='echo "use core dummy"'
alias cukes='rake cucumber'
